name: servicios_de_modelaje3d
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  model_viewer_plus: ^1.8.0
  provider: ^6.1.5
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1
  crypto: ^3.0.6
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3
  mailer: ^6.4.1
  flutter_dotenv: ^5.2.1
  exif: ^3.3.0
  image: ^4.5.4
  flutter_exif_rotation: ^0.5.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6
  flutter_swiper_view: ^1.1.8

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
    # Añade esto:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - .env
      - assets/images/Medevial.jpg
      - assets/images/Medieval.png
      - assets/images/Shooter.jpg
      - assets/images/Shooter.png
      - assets/images/Logo.png
      - assets/images/Adventura.png
      - assets/images/Fondo_main.jpeg
      - assets/images/AnimeImage.jpeg
      - assets/images/BossImage.jpeg
      - assets/images/WarImage.jpeg
      - assets/images/MedievalImage.jpeg
      - assets/images/LowPolyImage.jpg
      - assets/images/FotoPerfil.jpeg
      - assets/images/FotoPerfil2.jpeg
      - assets/images/FotoPerfil3.jpeg
      - assets/images/FotoPerfil4.jpeg
      - assets/images/proceso1.png
      - assets/images/proceso2.png
      - assets/images/proceso3.png
      - assets/images/sniper.png
      - assets/camaraman.glb
      - assets/Anime.glb
      - assets/Boss.glb
      - assets/LowPoly.glb
      - assets/Medieval.glb
      - assets/Shooter.glb
      - assets/model1.glb
      - assets/icons/Logo.png # Agrega el archivo de ícono aquí
android_12:
    # The image parameter sets the splash screen icon image.  If this parameter is not specified,
    # the app's launcher icon will be used instead.
    # Please note that the splash screen will be clipped to a circle on the center of the screen.
    # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
    # 640 pixels in diameter.
    # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
    # 768 pixels in diameter.  To fit a 1152x1152 image within a circle with a 768 diameter, simply 
    # ensure that the most important design elements of your image are placed within a circular area
    # with a 768 diameter at the center of the 1152x1152 canvas.
    #image: assets/android12splash.png

    # Splash screen background color.
    #color: "#42a5f5"

    # App icon background color.
    #icon_background_color: "#111111"

    # The branding property allows you to specify an image used as branding in the splash screen.
    #branding: assets/dart.png

    # The image_dark, color_dark, icon_background_color_dark, and branding_dark set values that
    # apply when the device is in dark mode. If they are not specified, the app will use the
    # parameters from above.  If there is no parameter above, the app will use the light mode values.
    #image_dark: assets/android12splash-invert.png
    #color_dark: "#042a49"
    #icon_background_color_dark: "#eeeeee"
flutter_native_splash:
    color: "#FFFFFF"
    image: assets/images/Medieval.png
    branding: assets/images/Medieval.png
    android: true
    ios: true
    web: false 
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_launcher_icons:
  android: "ic_launcher" # Generar iconos para Android o reemplaza el vigente
  ios: false # Solo para Android
  image_path: "assets/icons/Logo.png" # Ruta a tu archivo de icono
  min_sdk_android: 21 # Mínimo SDK de Android sopo